# ====================
# 家里环境配置
# ====================
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xyzw?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
          host: localhost   # 家里一般就是本机 redis
          port: 6379
          database: 0
          password:         # 如果有密码就在这里写
          timeout: 10s
          lettuce:
            pool:
              min-idle: 0
              max-idle: 8
              max-active: 8
              max-wait: -1ms

server:
  port: 8080

ocr:
  engine:
    # 家里的 OCR 地址（如果家里没搭服务，也可以指向内网、或者本机）
    url: http://172.28.41.154:5111

club:
  upload:
    path: ./upload
    # 家里访问上传文件的域名
    domain: http://localhost:8011
